"""Transparency label generation (planning.md §3).

Maps a verdict + confidence into reader-facing plain-language text. Three
variants — likely-AI, likely-human, uncertain — with wording that scales with
the confidence percentage and signal agreement, so a 48%% result reads
differently from an 81%% one and neither reads as an accusation.
"""

STRONG_CONF = 0.75   # at/above this, wording escalates from "indicates" to "strongly indicates"
HIGH_AGREE = 0.70    # at/above this, both signals are described as concurring


def _strength(confidence):
    return "strongly indicates" if confidence >= STRONG_CONF else "indicates"


def build_label(verdict, confidence, combined_score, agreement):
    """Return the transparency label string for a classified result.

    verdict: "ai" | "human" | "uncertain". confidence: float [0,1].
    combined_score: float [0,1] (direction). agreement: float [0,1] or None.
    """
    pct = round(confidence * 100)

    if verdict == "ai":
        if agreement is not None and agreement >= HIGH_AGREE:
            support = ("Both our writing-pattern check and our language-model "
                       "reviewer point the same way.")
        else:
            support = ("Our language-model reviewer flagged it, with partial "
                       "support from the writing-pattern analysis.")
        return (
            f"🤖 Likely AI-generated — {pct}% confidence. "
            f"Our analysis {_strength(confidence)} this text was produced by an "
            f"AI system. {support} This is an automated assessment, not a "
            f"certainty — if you're the creator and believe it's wrong, you can "
            f"appeal."
        )

    if verdict == "human":
        return (
            f"✍️ Likely human-written — {pct}% confidence. "
            f"Our analysis {_strength(confidence)} this text was written by a "
            f"person. We found the natural variation and voice typical of human "
            f"writing. This is an automated assessment, not a guarantee."
        )

    # uncertain
    lean = (", though it leans slightly toward AI" if combined_score >= 0.5
            else ", though it leans slightly toward human authorship")
    if agreement is not None and agreement < 0.5:
        agree_clause = "disagreed with each other"
    else:
        agree_clause = "weren't decisive enough to be sure"
    return (
        f"❓ Origin uncertain — {pct}% confidence. "
        f"We couldn't reliably determine whether this text was written by a "
        f"human or generated by AI{lean}. Our two checks {agree_clause}. Please "
        f"treat this as inconclusive — it isn't a judgment about the creator, "
        f"who can request a review."
    )
