"""Signal 2 — LLM classification via Groq (semantic).

Holistic judgment of whether text reads as machine-generated. Returns an
AI-likeness score in [0, 1] (higher = more AI-like) plus one-sentence reasoning.
On any API/parse error, returns score=None so fusion can fall back to stylometry
with a confidence penalty (planning.md §1).
"""

import json
import os

from groq import Groq

_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")

_SYSTEM = (
    "You are a forensic text analyst. Judge whether a passage was written by a "
    "human or generated by an AI language model. Weigh holistic semantic and "
    "stylistic cues: generic transitions, over-balanced hedging, safe phrasing "
    "and uniform polish lean AI; lived specificity, idiosyncrasy, and uneven "
    "voice lean human. Respond ONLY with JSON: "
    '{"ai_probability": <float 0..1>, "reasoning": "<one sentence>"}. '
    "ai_probability is your probability the text is AI-generated."
)


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


def llm_score(text, client=None):
    """Return {'score': float|None, 'reasoning': str} for the given text."""
    try:
        client = client or Groq(api_key=os.getenv("GROQ_API_KEY"))
        resp = client.chat.completions.create(
            model=_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM},
                {"role": "user", "content": text},
            ],
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        score = _clamp(float(data["ai_probability"]))
        reasoning = str(data.get("reasoning", "")).strip()
        return {"score": round(score, 4), "reasoning": reasoning}
    except Exception as e:  # noqa: BLE001 — degrade gracefully on any failure
        return {"score": None, "reasoning": f"error: {type(e).__name__}: {e}"}
